// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDU4_2536bjeo-RmV_jGuGR0ZqOkwJgDk',
    appId: '1:273934132035:web:32b3c3797fcebeb160c5f6',
    messagingSenderId: '273934132035',
    projectId: 'lecetdikit-ai',
    authDomain: 'lecetdikit-ai.firebaseapp.com',
    storageBucket: 'lecetdikit-ai.firebasestorage.app',
    measurementId: 'G-GJ19JW7RVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDztwOd9zTz4CAW4jV7FZJD5lNEeCZHDDs',
    appId: '1:273934132035:android:3157cc19f28c46f760c5f6',
    messagingSenderId: '273934132035',
    projectId: 'lecetdikit-ai',
    storageBucket: 'lecetdikit-ai.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ol7NnvsnnYQf0A-xsad90Omt3tFCAwA',
    appId: '1:273934132035:ios:75415004e33318ba60c5f6',
    messagingSenderId: '273934132035',
    projectId: 'lecetdikit-ai',
    storageBucket: 'lecetdikit-ai.firebasestorage.app',
    androidClientId: '273934132035-29c3lp7foe0omho0uoguhia0g169k1qs.apps.googleusercontent.com',
    iosClientId: '273934132035-ij3q36ci991edqlfdc3pvc5eqv974e7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.lecetdikit',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ol7NnvsnnYQf0A-xsad90Omt3tFCAwA',
    appId: '1:273934132035:ios:75415004e33318ba60c5f6',
    messagingSenderId: '273934132035',
    projectId: 'lecetdikit-ai',
    storageBucket: 'lecetdikit-ai.firebasestorage.app',
    androidClientId: '273934132035-29c3lp7foe0omho0uoguhia0g169k1qs.apps.googleusercontent.com',
    iosClientId: '273934132035-ij3q36ci991edqlfdc3pvc5eqv974e7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.lecetdikit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDU4_2536bjeo-RmV_jGuGR0ZqOkwJgDk',
    appId: '1:273934132035:web:c16cdbf1889d5e5e60c5f6',
    messagingSenderId: '273934132035',
    projectId: 'lecetdikit-ai',
    authDomain: 'lecetdikit-ai.firebaseapp.com',
    storageBucket: 'lecetdikit-ai.firebasestorage.app',
    measurementId: 'G-LG39VT7FF7',
  );
}
